"""Move representation and the record needed to undo a move.

A :class:`Move` describes *what* a player intends to do (and, once produced by
move generation, carries flags describing the kind of move it is). An
:class:`UndoRecord` captures the minimum state required to reverse a move so
that make/unmake can be used cheaply during AI search.
"""

from dataclasses import dataclass, field
from typing import Optional

from .constants import square_to_name


@dataclass
class Move:
    """A single chess move from one square to another.

    Attributes:
        from_square: (row, col) the moving piece starts on.
        to_square: (row, col) the moving piece lands on.
        is_capture: True if the move removes an opponent piece.
        is_en_passant: True if this is an en-passant pawn capture.
        castle_side: "king" or "queen" for a castling move, else None.
        promotion: Piece type a pawn promotes to, else None.
        is_double_pawn_push: True if a pawn advances two squares.
    """

    from_square: tuple
    to_square: tuple
    is_capture: bool = False
    is_en_passant: bool = False
    castle_side: Optional[str] = None
    promotion: Optional[str] = None
    is_double_pawn_push: bool = False

    def __str__(self):
        text = f"{square_to_name(self.from_square)}->{square_to_name(self.to_square)}"
        if self.promotion:
            text += f"={self.promotion}"
        return text

    def matches(self, from_square, to_square, promotion=None):
        """True if this move connects the given squares (and promotion if set).

        Used to reconcile a client's requested move with the fully-formed
        legal move generated by the engine.
        """
        if self.from_square != tuple(from_square) or self.to_square != tuple(to_square):
            return False
        if promotion is not None and self.promotion != promotion:
            return False
        return True


@dataclass
class UndoRecord:
    """Everything needed to reverse a single applied move."""

    move: Move
    captured_piece: object = None
    captured_square: Optional[tuple] = None
    prev_en_passant_target: Optional[tuple] = None
    prev_castling_rights: dict = field(default_factory=dict)
    prev_halfmove_clock: int = 0
    moved_piece_first_move: bool = False
    rook_move: Optional[tuple] = None  # (from_square, to_square) when castling
